### PR TITLE
Basket-based batch update

### LINKED ISSUE #1065: Basket Batch Update
As discussed here: [https://unitednations.sharepoint.com/sites/MarcEditorProject/_layouts/15/Doc.aspx?sourcedoc={8edfffcf-8684-429c-a49c-33788255cdcb}&action=edit&wd=target%28General.one%7C46b5c076-e444-4045-8ab5-41368ac3d971%2FEnhancements%7Cbe4cd68f-789c-4797-8c71-c28f23038172%2F%29&wdorigin=NavigationUrl](url)

Prototype here: [https://www.figma.com/proto/xmMyAnPg8YzjAkiWnh6ASM/Marc-Editor?type=design&node-id=1332-4315&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A2](url)

### PR DESCRIPTION
**Pull request by aaronhelton**
Closes #1065 and adds the basket batch update functionality.

Limitation: Removing items from the basket does not update the list of available records in the popup screen, but if you need to make sure they don't accidentally appear there, you can refresh the page before initiating the batch actions workflow.

### CODE REVIEW

**Review by Yalshire2004 — APPROVED** [review]
Ok perfect

**Comment by aaronhelton** [comment]
@jbukhari Do save actions happen when we save like this? Should we account for those?

**Comment by aaronhelton** [comment]
Need to check the interactivity and add the xref for authority controlled fields

**Comment by aaronhelton** [comment]
Also should check to see if we can save this record without validating (has 998, can be saved if invalid)

**Comment by jbukhari** [comment]
> @jbukhari Do save actions happen when we save like this? Should we account for those?

They are not currently running here, no. We can add them.

**Pull request merged**
