### PR TITLE
issue 1016 fixed

### LINKED ISSUE #1016: Remove 981 and 989 from all views

### PR DESCRIPTION
**Pull request by Yalshire2004**
Closes #1016

### CODE REVIEW

**Review by aaronhelton — COMMENTED** [review]
Please add .idea to .gitignore.

**Review by aaronhelton — APPROVED** [review]

**Review by jbukhari — COMMENTED** [review]
Suggestion for how to proceed with making fields read-only here https://github.com/dag-hammarskjold-library/dlx-rest/pull/1044

**Review by aaronhelton — COMMENTED** [review]
The only thing I see that's left to do is to disable the field and subfield hamburger menus when editable = false

**Comment by jbukhari** [comment]
> The only thing I see that's left to do is to disable the field and subfield hamburger menus when editable = false

Suggested updates here https://github.com/dag-hammarskjold-library/dlx-rest/pull/1050/files

**Review by jbukhari — COMMENTED** [review]
> The only thing I see that's left to do is to disable the field and subfield hamburger menus when editable = false

Suggested updates here https://github.com/dag-hammarskjold-library/dlx-rest/pull/1050/files

**Comment by aaronhelton** [comment]
This is superseded in #1046

**Pull request closed without merging**
