### PR TITLE
Update dlx logical fields config

### PR DESCRIPTION
**Pull request by jbukhari**
Updates logical field config and allows build-logical-fields script to operate on only specified fields

Includes dlx updates:

https://github.com/dag-hammarskjold-library/dlx/commit/4beacc115938c5a126c6c979501d88780bbf6eca
https://github.com/dag-hammarskjold-library/dlx/commit/b0415a43b5f6340cf12197854bbc26f998c8b364

### CODE REVIEW

**Review by aaronhelton — APPROVED** [review]

**Comment by aaronhelton** [comment]
The search is still not picking up all the fields. Reviewing.

**Comment by jbukhari** [comment]
> The search is still not picking up all the fields. Reviewing.

Upon further review, the logical field was not assigned as expected. In this case there should be two values in the logical field "subject". The second value should be `IRAQ--HUMAN RIGHTS`

image

**Comment by jbukhari** [comment]
> > The search is still not picking up all the fields. Reviewing.
> 
> Upon further review, the logical field was not assigned as expected. In this case there should be two values in the logical field "subject". The second value should be `IRAQ--HUMAN RIGHTS`

The build script has been run on the dev/qat database. The fields have been succesfully updated, and the search works as expected. Perhaps the script was run before on a different database, or without the latest code updates.

**Review by Yalshire2004 — APPROVED** [review]
Ok

**Pull request merged**
