### PR TITLE
Issue 871

### LINKED ISSUE #871: 998 fields should not be editable
They contain legacy data (record creation/last update in Horizon) that we need to preserve and don't want to be changed/deleted by mistake.

### LINKED ISSUE #1016: Remove 981 and 989 from all views

### PR DESCRIPTION
**Pull request by Yalshire2004**
Closes #871 
Closes #1016 

- I added a missing condition from Joseph's code allowing to edit the field
- I added the code to enable/disable the menus
- I added the code to enable/disable the checkboxes

### CODE REVIEW

**Review by aaronhelton — COMMENTED** [review]
Just need to add .vs to .gitignore so we don't end up with these extra files.

**Review by aaronhelton — APPROVED** [review]

**Review by jbukhari — COMMENTED** [review]
Small fix https://github.com/dag-hammarskjold-library/dlx-rest/pull/1051

**Comment by aaronhelton** [comment]
@jbukhari #1051 was merged in, so it should be ready for review again.

**Review by jbukhari — COMMENTED** [review]
https://github.com/dag-hammarskjold-library/dlx-rest/pull/1053

**Review by jbukhari — APPROVED** [review]

**Pull request merged**
