### PR TITLE
NOT xref; $ regex search; CSV serialization

### LINKED ISSUE #1346: NOT xref searches not working
The `NOT` is not being recognized by the search with xref searches, i.e. `NOT xref:273032`

### LINKED ISSUE #1438: `$` not working in regex search term
i.e. `191:/^A\/C.4\/SR.153$/` is not working. Whereas, `191:/^A\/C.4\/SR.153\b/` works

### PR DESCRIPTION
**Pull request by jbukhari**
Updates dlx to 1.4.4. Search fixes and enables formatting of result sets to CSV

* closes #1346 
* closes #1438

### CODE REVIEW

**Comment by aaronhelton** [comment]
@jbukhari is this ready for review?

**Review by aaronhelton — APPROVED** [review]

**Review by aaronhelton — APPROVED** [review]

**Review by aaronhelton — APPROVED** [review]

**Comment by aaronhelton** [comment]
@jbukhari if we bump both dlx (to 1.4.5) and urllib3 (to 1.26.19) we should be able to merge this in, and it should take care of the dependabot PR

**Comment by jbukhari** [comment]
Closing temporarily for more updates

**Comment by jbukhari** [comment]
Supercedes #1446

**Review by aaronhelton — APPROVED** [review]

**Review by aaronhelton — APPROVED** [review]

**Pull request merged**
