### PR TITLE
Add "created" option to sort

### LINKED ISSUE #1232: Add "created" as a sort option
Valeria pointed out that for speech record revision, the option to sort by record creation date is necessary; we currently only have updated:

image

I think it could be helpful for the other types of records as well, so it would be great if we could add "created" as another sort option everywhere.

### PR DESCRIPTION
**Pull request by aaronhelton**
Fixes #1232

### CODE REVIEW

**Comment by aaronhelton** [comment]
This depends on an index being created for the "created" field, which in turn necessitates an update to the build-indexes script. 

Additionally:
1. Records that originated in Horizon don't have a created field. This can be added via maintenance script if we need it.
2. Some dates in the created field were created as strings, not datetime objects, which could affect sorting.

**Comment by jbukhari** [comment]
The issue for created date format https://github.com/dag-hammarskjold-library/dlx-rest/issues/1013

**Comment by jbukhari** [comment]
issue for creating the database index for optimizing sort https://github.com/dag-hammarskjold-library/dlx/issues/248

**Comment by aaronhelton** [comment]
FYI, this does seem to work in dev right now, if you can get search results back.

**Review by Yalshire2004 — APPROVED** [review]
Ok

**Review by jbukhari — APPROVED** [review]

**Pull request merged**
